<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(id(, , u_3_9_XJ, , ))_u_3_9_XJ</name>
   <tag></tag>
   <elementGuidId>7f6b5c95-d70b-429b-b0d4-0cb1762b466e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_3_9_XJ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='u_3_9_XJ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>df938713-3adc-4711-a202-765cafec8458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_8idr img</value>
      <webElementGuid>4fa37bc7-3486-4217-b3dc-289fdbdbb5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.xx.fbcdn.net/rsrc.php/v3/yO/r/zgulV2zGm8t.png</value>
      <webElementGuid>7b71efa4-d57c-4ee1-8803-a8d62e85ac31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>efb4b297-c861-4f26-90d3-1816e9a7c7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>f49a9951-4517-414f-b3a3-3f354f52f00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_3_9_XJ</value>
      <webElementGuid>d5d961cd-d524-4473-aa00-b5afd04beb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_3_9_XJ&quot;)</value>
      <webElementGuid>aa8f2de3-98aa-4aca-a5d4-dd16b525c4ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='u_3_9_XJ']</value>
      <webElementGuid>156840d8-4d30-43dd-8104-655062b9dbfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='facebook']/body/div[4]/div[2]/div/div/img</value>
      <webElementGuid>998f74bc-d453-44a1-a4cc-0baa750062a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://static.xx.fbcdn.net/rsrc.php/v3/yO/r/zgulV2zGm8t.png')]</value>
      <webElementGuid>671f5cbd-4636-4648-89f6-68e7c9f0c52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>73724355-1e9c-4656-9bef-a50979788f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.xx.fbcdn.net/rsrc.php/v3/yO/r/zgulV2zGm8t.png' and @id = 'u_3_9_XJ']</value>
      <webElementGuid>2a73445b-c684-4f17-9d85-85a8eac6ab09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
