<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Custom_mrm _5dbc _8esb img sp_98fCI7IVTTz_f00bf3</name>
   <tag></tag>
   <elementGuidId>4ffe7405-7965-423e-aa6d-a550ab87c74f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mrm._5dbc._8esb.img.sp_98fCI7IVTTz_1_5x.sx_e1ddd6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_2_p_Pp']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6ec8cdd4-1d7d-4cb1-800c-f02a5ac9318b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mrm _5dbc _8esb img sp_98fCI7IVTTz_1_5x sx_e1ddd6</value>
      <webElementGuid>117b900d-2a39-40f4-a7bd-f437661bedce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_2_p_Pp&quot;)/i[@class=&quot;mrm _5dbc _8esb img sp_98fCI7IVTTz_1_5x sx_e1ddd6&quot;]</value>
      <webElementGuid>bce2ee52-eb43-40f1-87e6-61569d4408f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_2_p_Pp']/i</value>
      <webElementGuid>c7916e66-4106-437e-81b3-003294deacea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/i</value>
      <webElementGuid>bd1dfbb9-90a5-4f7d-acc3-d336fcb4eba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
