<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your pronounShe Wish her a ha_90e2d2</name>
   <tag></tag>
   <elementGuidId>8d9defb7-1881-4be8-b760-d8f52d2d87dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js_ct</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='js_ct']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>38d9831f-ae41-44e8-865b-96d346303102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select your pronoun</value>
      <webElementGuid>bdec03a7-7dcd-4707-a03d-054776762386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preferred_pronoun</value>
      <webElementGuid>b07d0589-6892-4269-a17c-1020d252d448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7-16 _9hk6 _5dba _5f0v</value>
      <webElementGuid>a3f507f9-f105-4b33-a548-cd5508f4c280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js_ct</value>
      <webElementGuid>b9577e66-1041-48ca-be15-2bd7f39818b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa76db10-a249-4f3c-a435-198f198e459c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your pronounShe: &quot;Wish her a happy birthday!&quot;He: &quot;Wish him a happy birthday!&quot;They: &quot;Wish them a happy birthday!&quot;</value>
      <webElementGuid>42b2fd1c-8a95-485a-854a-f654c2b974dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_ct&quot;)</value>
      <webElementGuid>ed1ec380-fb0e-48b0-b169-0ba43feefd32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='js_ct']</value>
      <webElementGuid>242c5149-b161-4855-8807-5c335f33b6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_2_p_Pp']/select</value>
      <webElementGuid>a4129d5d-5c0a-4880-a01f-cfc02693c55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom'])[1]/following::select[1]</value>
      <webElementGuid>8bc2b5c2-29f5-4482-b61a-ebb71c6c9699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[1]/following::select[1]</value>
      <webElementGuid>005bff2e-faa8-4501-a968-193ba890ca67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your pronoun is visible to everyone.'])[1]/preceding::select[1]</value>
      <webElementGuid>dbdf6ee0-7bc5-4f2b-b4b7-c91df53271c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::select[1]</value>
      <webElementGuid>35c51e90-31f3-4bfc-b281-2f80927982c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>b7cb6bfd-08aa-417b-abaa-b2c78ee9294a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'preferred_pronoun' and @id = 'js_ct' and (text() = 'Select your pronounShe: &quot;Wish her a happy birthday!&quot;He: &quot;Wish him a happy birthday!&quot;They: &quot;Wish them a happy birthday!&quot;' or . = 'Select your pronounShe: &quot;Wish her a happy birthday!&quot;He: &quot;Wish him a happy birthday!&quot;They: &quot;Wish them a happy birthday!&quot;')]</value>
      <webElementGuid>8aec3406-82bd-4a22-935f-0f94b6b2592e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
